[package]
name = "il-pleut"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1.0", features = ["full"] }
url = "2.2"
rand = "0.8"
sha1 = "0.10"
percent-encoding = "2.3.2"
